version: '3.8'
services:
  ui:
    env_file:
      - "./ui/.env"
    build:
      context: .
      dockerfile: ./ui/Dockerfile
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: always
    volumes:
      - ./ui:/app
      - /app/node_modules
  api:
    stdin_open: true
    env_file:
      - "./api/.env"
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: dev
    ports:
      - "1337:1337"
    restart: always
    volumes:
      - ./api:/app
      - /app/node_modules
