version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=tyler
      - POSTGRES_PASSWORD=apollo
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  ui:
    env_file: "./ui/.env.dev"
    build:
      context: ./ui
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
  api:
    stdin_open: true
    env_file: "./api/.env.dev"
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "1337:1337"
    restart: always

  version: "3.8"
