apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: DATABASE_URL
          - name: DIRECT_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: DIRECT_URL
          - name: ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: api
                key: ACCESS_TOKEN_SECRET
          - name: REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: api
                key: REFRESH_TOKEN_SECRET
