apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tableflight-stage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: stage.tableflight.com
      http:
        paths:
          - path: /graphql(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 1337
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 1337
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tableflight-stage-tls
