import { defineConfig, devices } from '@playwright/test'
import { nxE2EPreset } from '@nx/playwright/preset'

// The UI dev server runs on 5173 and, via the `dev` configuration, loads
// `.env.dev` (which provides VITE_API_URL). Override with BASE_URL in CI.
const baseURL = process.env['BASE_URL'] || 'http://localhost:5173'

export default defineConfig({
  ...nxE2EPreset(__filename, { testDir: './src' }),
  use: {
    baseURL,
    trace: 'on-first-retry',
  },
  // reuseExistingServer everywhere: nx's atomized e2e-ci targets run several
  // playwright processes in parallel, and only the first may bind the ports.
  webServer: [
    {
      command: 'npx nx run ui:serve:dev',
      url: 'http://localhost:5173',
      reuseExistingServer: true,
      timeout: 120 * 1000,
    },
    {
      // Static server over the repo root for the wasm board-engine harness
      // (src/harness/index.html imports libs/board-engine/pkg directly).
      // Readiness probes a file that always exists — pkg/ is generated by
      // board-engine:build (an nx dependency of the e2e targets).
      command: 'python3 -m http.server 4301 --bind 127.0.0.1 --directory ../..',
      url: 'http://localhost:4301/package.json',
      reuseExistingServer: true,
      timeout: 30 * 1000,
    },
  ],
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
})
