replicaCount: 3
image:
  repository: 905418147010.dkr.ecr.us-east-2.amazonaws.com/api
  tag: ''
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  host: api.stage.tableflight.com
  certIssuer: letsencrypt-prod
env:
  - NODE_ENV
  - DATABASE_URL
  - DIRECT_URL
  - ACCESS_TOKEN_SECRET
  - REFRESH_TOKEN_SECRET
