replicaCount: 3
image:
  repository: 905418147010.dkr.ecr.us-east-2.amazonaws.com/api
  tag: ''
service:
  type: LoadBalancer
  port: 1337
ingress:
  enabled: true
  host: api-stage.tableflight.com
  certIssuer: letsencrypt-prod
